"""
Export a fitted BVFF to LAMMPS.

The mapping is exact (not approximate) for every term of the adopted model:

  - **BV** is mathematically an EAM functional — V_i = Σ_j V_ij(r) is a
    pair-specific density and E = Σ_i S_i (V_i − V0_i)² an embedding function
    — so it exports losslessly to mainline ``pair_style eam/fs`` tables
    (F(ρ) = S(ρ−V0)², ρ_ij(r) = V_ij(r) with the C² taper baked in).
  - **Buckingham / r⁻¹² repulsion** (inner guard + taper included) go into
    the eam/fs pair-potential table φ(r).
  - **Coulomb/Ewald** uses native ``coul/long`` + ``kspace_style ewald``
    (tinfoil boundary, like the Python default).
  - **BVV** is a vector density — not expressible in mainline LAMMPS — and
    ships as the ``pair_style bvv`` plugin in ``lammps_plugin/`` (EAM-like
    two-pass C++, literal transcription of the Python force kernel).

Tables are generated by evaluating the SAME Python classes used in fitting,
so guard radii, taper, and functional forms cannot drift.

Run from a fit directory (controls.toml + output/fitted_parameters.toml):

    bvff-export-lammps [--out lammps_export] [--frame 0]
    bvff-export-lammps --validate --lmp /path/to/lmp

Known small constants gap: LAMMPS metal units use qqr2e = 14.399645 eV·Å/e²
vs this code's 14.3996 (3.2e-6 relative) — a few meV on a 40-atom cell's
Coulomb energy; forces agree to ~1e-4 eV/Å.
"""
from __future__ import annotations

import logging
from pathlib import Path

import numpy as np

from bvff.core.potentials import BV, Buckingham

# Repository root (editable install): the LAMMPS plugin is built in lammps_plugin/.
_PROJECT_ROOT = Path(__file__).resolve().parents[2]


NRHO, NR = 2000, 2000
RHO_MAX  = 20.0     # generous: max valence sums seen in MD are ~5


def _pair_key(params: dict, e1: str, e2: str):
    return f"{e1}-{e2}" if f"{e1}-{e2}" in params else (
        f"{e2}-{e1}" if f"{e2}-{e1}" in params else None)


def _phi_table(fitted, e1: str, e2: str, r: np.ndarray) -> np.ndarray:
    """Short-range pair energy φ(r) on the grid: guarded+tapered Buckingham
    plus (if enabled) the tapered r⁻¹² repulsion. Evaluated through the same
    classes the fit used."""
    phi = np.zeros_like(r)
    rg  = np.maximum(r, 1e-9)
    bpairs = {k: {"A": v.A, "rho": v.rho, "C": v.C}
              for k, v in fitted.buckingham.pairs.items()}
    if _pair_key(bpairs, e1, e2):
        buck = Buckingham(params=bpairs, cutoff=fitted.cutoff,
                          smooth_width=fitted.smooth_width)
        with np.errstate(divide="ignore", over="ignore", invalid="ignore"):
            p, _ = buck._pair_phi([e1, e2],
                                  np.zeros(rg.size, dtype=np.int64),
                                  np.ones(rg.size, dtype=np.int64), rg)
        phi += p
    key = _pair_key(fitted.repulsive.B, e1, e2)
    if key and fitted.repulsive.B[key] != 0.0:
        from bvff.core.potentials import _switch
        # r⁻¹² diverges at r→0 and has no guard: clamp the table below 0.2 Å
        # (physically unreachable; keeps the spline finite).
        rr = np.maximum(rg, 0.2)
        S, _ = _switch(rr, fitted.cutoff, fitted.smooth_width)
        phi += fitted.repulsive.B[key] / rr**12 * S
    return phi


def write_eam_fs(fitted, elems: list[str], path: Path, bv_form: str) -> None:
    from ase.data import atomic_numbers, atomic_masses

    cutoff = fitted.cutoff
    dr     = cutoff / (NR - 1)
    drho   = RHO_MAX / (NRHO - 1)
    r      = np.arange(NR) * dr
    rho_ax = np.arange(NRHO) * drho

    bv = BV(
        species_params={a: {"V0": s.V0, "S": s.S} for a, s in fitted.BV.species.items()},
        pair_params={k: {"r0": p.r0, "C": p.C, "b": p.b} for k, p in fitted.BV.pairs.items()},
        cutoff=cutoff, form=bv_form, smooth_width=fitted.smooth_width,
    )
    bv_pp = {k: (p.r0, p.C, p.b) for k, p in fitted.BV.pairs.items()}

    def density(e1, e2):
        key = _pair_key(bv_pp, e1, e2)
        if key is None:
            return np.zeros_like(r)
        r0, C, b = bv_pp[key]
        rg = np.maximum(r, 1e-6)          # power form diverges at r = 0
        V, _ = bv._valence_and_deriv(rg, np.full_like(rg, r0),
                                     np.full_like(rg, C), np.full_like(rg, b))
        return V

    def embedding(e):
        sp = fitted.BV.species.get(e)
        if sp is None:
            return np.zeros_like(rho_ax)
        return sp.S * (rho_ax - sp.V0) ** 2

    def fmt(arr):
        out = []
        for k in range(0, arr.size, 5):
            out.append("".join(f"{v:24.16E}" for v in arr[k:k + 5]))
        return "\n".join(out)

    lines = [
        "M3L BVFF export: BV term as Finnis-Sinclair EAM (F = S*(rho-V0)^2,",
        "rho_ij = V_ij with C2 cutoff taper) + guarded/tapered Buckingham(+r^-12)",
        "as the pair table. Generated by bvff/tools/export_lammps.py.",
        f"{len(elems)} " + " ".join(elems),
        f"{NRHO} {drho:.16E} {NR} {dr:.16E} {cutoff:.16E}",
    ]
    for e in elems:
        lines.append(f"{atomic_numbers[e]} {atomic_masses[atomic_numbers[e]]:.6f} "
                     f"0.0 none")
        lines.append(fmt(embedding(e)))
        for e2 in elems:
            lines.append(fmt(density(e, e2)))
    for i, e1 in enumerate(elems):
        for e2 in elems[: i + 1]:
            lines.append(fmt(r * _phi_table(fitted, e1, e2, r)))   # r*phi convention
    path.write_text("\n".join(lines) + "\n")


def write_bvv(fitted, path: Path, bv_form: str) -> None:
    sp = {a: (s.W0, s.D) for a, s in fitted.BVV.species.items()
          if s.D != 0.0 or s.W0 != 0.0}
    pp = {k: (p.r0, p.C, p.b) for k, p in fitted.BVV.pairs.items()}
    lines = [
        "# BVV parameters for pair_style bvv (see lammps_plugin/)",
        f"cutoff        {fitted.cutoff}",
        f"smooth_width  {fitted.smooth_width}",
        f"form          {bv_form}",
        f"species       {len(sp)}",
    ]
    for a, (w0, d) in sp.items():
        lines.append(f"{a}  {w0:.16g}  {d:.16g}")
    lines.append(f"pairs         {len(pp)}")
    for k, (r0, C, b) in pp.items():
        e1, e2 = k.split("-")
        lines.append(f"{e1} {e2}  {r0:.16g} {C:.16g} {b:.16g}")
    path.write_text("\n".join(lines) + "\n")


def write_data(frame, elems: list[str], charges: dict, path: Path) -> None:
    from ase.data import atomic_numbers, atomic_masses
    lat = np.asarray(frame.lattice, dtype=float)
    if np.abs(lat - np.diag(np.diag(lat))).max() > 1e-10:
        raise ValueError("export currently supports orthogonal cells only "
                         f"(got off-diagonal lattice {lat}).")
    cart = np.asarray(frame.positions, dtype=float) @ lat
    t_of = {e: i + 1 for i, e in enumerate(elems)}
    lines = [
        "M3L BVFF export (bvff/tools/export_lammps.py)", "",
        f"{len(frame.species)} atoms",
        f"{len(elems)} atom types", "",
        f"0.0 {lat[0, 0]:.16g} xlo xhi",
        f"0.0 {lat[1, 1]:.16g} ylo yhi",
        f"0.0 {lat[2, 2]:.16g} zlo zhi", "",
        "Masses", "",
    ]
    for e in elems:
        lines.append(f"{t_of[e]} {atomic_masses[atomic_numbers[e]]:.6f}  # {e}")
    lines += ["", "Atoms  # charge", ""]
    for i, (s, p) in enumerate(zip(frame.species, cart), start=1):
        lines.append(f"{i} {t_of[s]} {charges.get(s, 0.0):.10g} "
                     f"{p[0]:.16g} {p[1]:.16g} {p[2]:.16g}")
    path.write_text("\n".join(lines) + "\n")


def write_input(fitted, elems: list[str], out: Path, plugin: str,
                use_bvv: bool) -> None:
    el = " ".join(elems)
    bvv_lines = (
        f"plugin load {plugin}\n"
        f"pair_style hybrid/overlay eam/fs coul/long {fitted.cutoff} bvv\n"
        f"pair_coeff * * eam/fs bvff.eam.fs {el}\n"
        "pair_coeff * * coul/long\n"
        f"pair_coeff * * bvv bvff.bvv {el}\n"
    ) if use_bvv else (
        f"pair_style hybrid/overlay eam/fs coul/long {fitted.cutoff}\n"
        f"pair_coeff * * eam/fs bvff.eam.fs {el}\n"
        "pair_coeff * * coul/long\n"
    )
    (out / "in.bvff").write_text(
        "# M3L BVFF — exported potential (single point; extend for MD)\n"
        "units metal\natom_style charge\nboundary p p p\n"
        "read_data bvff.data\n"
        + bvv_lines +
        "kspace_style ewald 1.0e-6\n"
        "neighbor 1.0 bin\n"
        "thermo_style custom step temp pe ke etotal press\n"
        "dump f all custom 1 forces.dump id fx fy fz\n"
        "dump_modify f sort id format float %20.13g\n"
        "run 0\n"
    )


def export(fit_dir: str = ".", out_dir: str = "lammps_export",
           frame_index: int = 0, plugin: str | None = None):
    """Export the fit in ``fit_dir``. Dataset paths in its controls.toml are
    relative to the fit directory, so work from there — but restore the
    caller's cwd afterwards. A relative ``out_dir`` is taken relative to
    ``fit_dir``; the returned path is absolute."""
    import os
    prev = os.getcwd()
    os.chdir(fit_dir)
    try:
        return _export(out_dir, frame_index, plugin)
    finally:
        os.chdir(prev)


def _export(out_dir: str, frame_index: int, plugin: str | None):
    from bvff.parsers.controls_parser   import parse_controls
    from bvff.parsers.parameters_parser import parse_parameters
    from bvff.parsers.dataset           import load_dataset

    controls = parse_controls("controls.toml")
    fitted   = parse_parameters("output/fitted_parameters.toml", validate=True)
    pc       = controls.potentials

    if pc.use_angle:
        raise ValueError("use_angle=1 is not exportable yet (no LAMMPS analogue "
                         "of the tapered O-O-O term).")
    if pc.use_coulomb and not controls.extensions.use_ewald:
        raise ValueError("export assumes Ewald electrostatics (coul/long); "
                         "direct tapered Coulomb has no LAMMPS analogue.")

    # Logs only when a CLI configured the 'bvff' logger (see main()).
    frames = load_dataset(entries=controls.dataset,
                          logger=logging.getLogger("bvff")).frames
    frame  = frames[frame_index]
    elems  = sorted(set(frame.species))

    use_bvv = pc.use_BVV and any(
        s.D != 0.0 for s in fitted.BVV.species.values())
    if plugin is None:
        cand = _PROJECT_ROOT / "lammps_plugin" / "bvvplugin.so"
        plugin = str(cand) if cand.exists() else "./bvvplugin.so"

    out = Path(out_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    write_eam_fs(fitted, elems, out / "bvff.eam.fs", pc.bv_form)
    if use_bvv:
        write_bvv(fitted, out / "bvff.bvv", pc.bv_form)
    write_data(frame, elems, fitted.coulomb.charges, out / "bvff.data")
    write_input(fitted, elems, out, plugin, use_bvv)
    return out, frame, controls, fitted


def validate(out: Path, frame, controls, fitted, lmp: str) -> dict:
    """Single-point E/F comparison: exported LAMMPS files vs the Python
    reference on the same structure."""
    import subprocess
    from bvff.core.main import build_bvff

    res = subprocess.run([lmp, "-in", "in.bvff", "-log", "log.validate"],
                         cwd=out, capture_output=True, text=True)
    if res.returncode != 0:
        raise RuntimeError(f"lmp failed:\n{res.stdout[-2000:]}\n{res.stderr[-500:]}")
    pe = None
    for line in (out / "log.validate").read_text().splitlines():
        tok = line.split()
        if len(tok) >= 4 and tok[0] == "0" and pe is None:
            try:
                pe = float(tok[2])          # step temp pe ...
            except ValueError:
                pass
    f_lmp = np.loadtxt(out / "forces.dump", skiprows=9)[:, 1:4]

    bvff = build_bvff(controls, fitted)
    e_py, f_py = bvff.energy_and_forces(frame.lattice, frame.species, frame.positions)
    return {
        "E_lammps": pe, "E_python": e_py, "dE": pe - e_py,
        "dE_per_atom_meV": (pe - e_py) / len(frame.species) * 1000,
        "F_max_dev": float(np.abs(f_lmp - f_py).max()),
        "F_rms_dev": float(np.sqrt(np.mean((f_lmp - f_py) ** 2))),
    }


def main():
    import argparse
    from bvff.core.outputs import cli_logger
    cli_logger()
    ap = argparse.ArgumentParser(description="Export a fitted BVFF to LAMMPS.")
    ap.add_argument("--out", default="lammps_export")
    ap.add_argument("--frame", type=int, default=0)
    ap.add_argument("--plugin", default=None,
                    help="path to bvvplugin.so (default: repo lammps_plugin/)")
    ap.add_argument("--validate", action="store_true")
    ap.add_argument("--lmp", default=None, help="LAMMPS binary for --validate")
    args = ap.parse_args()

    out, frame, controls, fitted = export(
        out_dir=args.out, frame_index=args.frame, plugin=args.plugin)
    print(f"Exported to {out}/: bvff.eam.fs, bvff.bvv, bvff.data, in.bvff")
    if args.validate:
        if not args.lmp:
            raise SystemExit("--validate needs --lmp /path/to/lmp")
        r = validate(out, frame, controls, fitted, args.lmp)
        print(f"E: lammps {r['E_lammps']:.6f} eV | python {r['E_python']:.6f} eV "
              f"| dE {r['dE_per_atom_meV']:+.3f} meV/atom")
        print(f"F: max dev {r['F_max_dev']:.2e} eV/Å | rms dev {r['F_rms_dev']:.2e} eV/Å")


if __name__ == "__main__":
    main()
