"""
Generate a DFT training-structure set (POSCARs) for fitting a *ferroelectric*
PbTiO3 bond-valence force field.

The existing AIMD parquet data are thermal NVT snapshots at a single volume — they
constrain the ferroelectric energy landscape only weakly: an unregularized E+F fit
to them can land on a paraelectric or bound-saturated optimum (the 2026-07 refits
needed a Tikhonov pull toward the physical seed to keep the double well; every fit
now records its verdict in output/ferroelectric_validation.toml). This script
produces the static structures that constrain the landscape *directly*:

  cubic_eos/    cubic Pm-3m at several volumes      → equilibrium volume, bulk modulus
  tetragonal_gs/ P4mm ferroelectric ground state     → the polar minimum
  double_well/  polar path λ=-1..+1 (cubic at λ=0)   → the ferroelectric DOUBLE WELL
  ca_scan/      tetragonality c/a at fixed volume    → strain–polarization coupling

Each structure goes in its own directory with a single POSCAR, ready for a VASP
static (single-point) run. After DFT, collect the vasprun.xml files (or convert
to extxyz/parquet) and refit — see the generated README.

Usage:
    bvff-gen-poscars                 # default set under examples/PbTiO3/dft_set
    bvff-gen-poscars --supercell 2 2 2
    bvff-gen-poscars --out somewhere/ --eos-points 9 --dw-images 13
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
from ase import Atoms
from ase.io import write


# ──────────────────────────────────────────────
# PbTiO3 crystallography
# ──────────────────────────────────────────────
#
# Pb-at-corner setting (matches bvff.tools.ferroelectric.ideal_perovskite):
#   Pb (A) at the corner, Ti (B) at the body centre, O on the faces.
#
# Cubic (paraelectric) lattice constant near Tc, and tetragonal P4mm
# room-temperature structure (Nelmes & Kuhs, Solid State Commun. 54, 721 (1985):
# a=3.9039, c=4.1348 Å; Ti z=0.538, O1 z=0.112, O2 z=0.612).

A_CUBIC = 3.969          # Å, cubic PbTiO3 near the transition
A_TETRA = 3.904          # Å
C_TETRA = 4.152          # Å

CUBIC_BASIS = [
    ("Pb", (0.0, 0.0, 0.0)),
    ("Ti", (0.5, 0.5, 0.5)),
    ("O",  (0.5, 0.5, 0.0)),   # apical (along c)
    ("O",  (0.5, 0.0, 0.5)),   # equatorial
    ("O",  (0.0, 0.5, 0.5)),   # equatorial
]

# P4mm polar displacements: same atom order as CUBIC_BASIS.
TETRA_BASIS = [
    ("Pb", (0.0, 0.0, 0.000)),
    ("Ti", (0.5, 0.5, 0.538)),
    ("O",  (0.5, 0.5, 0.112)),
    ("O",  (0.5, 0.0, 0.612)),
    ("O",  (0.0, 0.5, 0.612)),
]


def _build(basis, cell, supercell) -> Atoms:
    symbols = [s for s, _ in basis]
    scaled  = [p for _, p in basis]
    atoms   = Atoms(symbols=symbols, scaled_positions=scaled, cell=cell, pbc=True)
    return atoms.repeat(tuple(supercell))


def cubic(a, supercell=(1, 1, 1)) -> Atoms:
    return _build(CUBIC_BASIS, [[a, 0, 0], [0, a, 0], [0, 0, a]], supercell)


def tetragonal(a, c, supercell=(1, 1, 1)) -> Atoms:
    return _build(TETRA_BASIS, [[a, 0, 0], [0, a, 0], [0, 0, c]], supercell)


def double_well_path(a, c, supercell=(1, 1, 1), n_images=11):
    """Polar interpolation at the (fixed) tetragonal cell: centrosymmetric cubic
    coords at λ=0, the two polar variants at λ=±1. DFT energy vs λ is the
    ferroelectric double well."""
    cell  = [[a, 0, 0], [0, a, 0], [0, 0, c]]
    centro = _build(CUBIC_BASIS, cell, supercell)   # cubic coords in the tetragonal cell
    polar  = _build(TETRA_BASIS, cell, supercell)
    f0 = centro.get_scaled_positions()
    df = polar.get_scaled_positions() - f0
    df -= np.round(df)                               # minimal-image displacement
    out = []
    for lam in np.linspace(-1.0, 1.0, n_images):
        at = centro.copy()
        at.set_scaled_positions(f0 + lam * df)
        out.append((float(lam), at))
    return out


def _write_poscar(atoms: Atoms, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    write(str(path), atoms, format="vasp", direct=True, sort=True)


README = """\
# PbTiO3 DFT training-structure set (for ferroelectric BVFF fitting)

Generated by `bvff/tools/gen_poscars.py`. These structures supply the ferroelectric
energy landscape that the thermal AIMD parquet data lack. Run a VASP **static**
(single-point, `NSW=0`/`IBRION=-1`) calculation in each directory.

## Groups
- `cubic_eos/a_*`     — cubic Pm-3m at several volumes → equilibrium volume + bulk modulus.
- `tetragonal_gs/`    — P4mm ferroelectric ground state (polar minimum).
- `double_well/lam_*` — polar path, λ=-1..+1 (cubic/centrosymmetric at λ=0).
                        E(λ) is the ferroelectric DOUBLE WELL — the key target.
- `ca_scan/ca_*`      — tetragonality c/a at fixed volume → strain–polarization coupling.

## Suggested DFT settings (PBEsol or PBE; adjust to your setup)
- ENCUT ≥ 500 eV; KSPACING ~0.25 (or k-mesh ≥ 6×6×6 per 5-atom cell).
- Static run: `IBRION=-1`, `NSW=0`, `LWAVE=.FALSE.`, accurate forces (`ADDGRID=.TRUE.`, `PREC=Accurate`).
- Keep the SAME ENCUT/KSPACING/PP across ALL structures (the FF fit compares their
  energies — a constant offset is removed in the loss, but settings must be consistent).
- Write forces and stress (default in vasprun.xml).

## Refit workflow
1. Run DFT in every leaf directory → each yields a `vasprun.xml`.
2. Point the BVFF dataset at them (a list of vasprun.xml works), or convert to a
   single `.extxyz`. Mix with the existing AIMD parquet for thermal coverage.
3. In `controls.toml`: keep `fit_charges = 0` and physical fixed charges; use a
   soft `use_buckingham = 1` repulsion (r^-12 cannot balance formal-charge Coulomb).
4. Refit (`bvff-fit`), then validate the result with
   `bvff-ferroelectric` (double well, polarization, MD stability).
"""


def generate(out_dir, supercell=(1, 1, 1), eos_points=7, dw_images=11):
    out = Path(out_dir)
    n_written = 0

    # 1) Cubic EOS — isotropic volume scan.
    for a in np.linspace(3.85, 4.10, eos_points):
        _write_poscar(cubic(a, supercell), out / "cubic_eos" / f"a_{a:.3f}" / "POSCAR")
        n_written += 1

    # 2) Tetragonal P4mm ground state.
    _write_poscar(tetragonal(A_TETRA, C_TETRA, supercell), out / "tetragonal_gs" / "POSCAR")
    n_written += 1

    # 3) Double-well polar path (fixed tetragonal cell).
    for lam, at in double_well_path(A_TETRA, C_TETRA, supercell, dw_images):
        _write_poscar(at, out / "double_well" / f"lam_{lam:+.2f}" / "POSCAR")
        n_written += 1

    # 4) c/a scan at fixed volume V0 = a_t^2 c_t.
    V0 = A_TETRA**2 * C_TETRA
    for ca in (1.00, 1.02, 1.04, 1.064, 1.08):
        a = (V0 / ca) ** (1.0 / 3.0)
        c = ca * a
        _write_poscar(tetragonal(a, c, supercell), out / "ca_scan" / f"ca_{ca:.3f}" / "POSCAR")
        n_written += 1

    (out).mkdir(parents=True, exist_ok=True)
    (out / "README.md").write_text(README)
    return n_written, out


def main():
    ap = argparse.ArgumentParser(description="Generate DFT POSCAR set for ferroelectric BVFF fitting.")
    ap.add_argument("--out", default="examples/PbTiO3/dft_set", help="output directory")
    ap.add_argument("--supercell", nargs=3, type=int, default=[1, 1, 1],
                    help="supercell repetition (e.g. 2 2 2 to match the AIMD cell)")
    ap.add_argument("--eos-points", type=int, default=7, help="cubic EOS volume points")
    ap.add_argument("--dw-images", type=int, default=11, help="double-well path images")
    args = ap.parse_args()

    n, out = generate(args.out, tuple(args.supercell), args.eos_points, args.dw_images)
    print(f"Wrote {n} POSCAR structures under {out}/  (supercell={tuple(args.supercell)})")
    print(f"See {out}/README.md for DFT settings and the refit workflow.")


if __name__ == "__main__":
    main()
