cutoff = 6.0
smooth_width = 1.0

[coulomb]
Pb = 1.4
Ti = 1.0
O = -0.8

[buckingham.O-O]
A = 22764.0
rho = 0.149
C = 27.88

[buckingham.O-Pb]
A = 4510.0
rho = 0.32
C = 0.0

[BV.species.Pb]
V0 = 2.0
S = 0.5

[BV.species.Ti]
V0 = 4.0
S = 0.5

[BV.species.O]
V0 = 2.0
S = 0.5

[BV.pairs.O-Pb]
r0 = 2.112
C = 6.0
b = 0.37

[BV.pairs.O-Ti]
r0 = 1.815
C = 5.2
b = 0.37

[BVV.Pb]
W0 = 0.5
D = 0.1

[BVV.Ti]
W0 = 0.3
D = 0.1

[BVV.pairs.O-Pb]
r0 = 2.112
C = 6.0
b = 0.37

[BVV.pairs.O-Ti]
r0 = 1.815
C = 5.2
b = 0.37
